/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddSite.java
 *
 * Created on Feb 8, 2011, 12:35:38 PM
 */
package swapmonitor;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kamol
 */
public class AddSite extends javax.swing.JFrame {

    static final String DRIVER = "net.sourceforge.jtds.jdbcx.JtdsDataSource";
    static final String DATABASE_URL = "jdbc:jtds:sqlserver://GP-PC-1005484:1433/RTinfo";
    Connection connection = null;
    PreparedStatement pst = null;

    /** Creates new form AddSite */
    public AddSite() {
        super("AddSite");
        setLocationRelativeTo(null);
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTA.setColumns(20);
        JTA.setRows(5);
        jScrollPane1.setViewportView(JTA);

        jButton1.setText("Add To Database");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName(DRIVER);
            connection = DriverManager.getConnection(DATABASE_URL, "mk5", "mk5mnm");
            if (JTA.getText().length() > 5) {
                String sql = "delete from rtinfo.dbo.swapmonitorsite";
                pst = connection.prepareStatement(sql);
                pst.executeUpdate();
                pst.close();

                String SiteList = JTA.getText();
                String[] SiteName = SiteList.split("\n");
                for (int i = 0; i < SiteName.length; i++) {
                    if (SiteName[i].trim().length() > 2) {
                        sql = "insert into rtinfo.dbo.swapmonitorsite(SiteName) values(?)";
                        pst = connection.prepareStatement(sql);
                        pst.clearParameters();
                        pst.setObject(1, SiteName[i].trim());
                        pst.executeUpdate();
                        pst.close();
                    }
                }
                JOptionPane.showMessageDialog(null, "Site successfully added to database \n GP-PC-1005484\\RTinfo\\SwapMonitorSite", "Completion Message", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Given input can't be less than 6 letter", "Input Error:", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Problem while parsing input text", "Input Error:", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddSite().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
