/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * southPanel.java
 *
 * Created on Feb 10, 2011, 3:10:13 PM
 */

package swapmonitor;
import java.awt.Toolkit;
import java.awt.Dimension;
/**
 *
 * @author kamol
 */
public class southPanel extends javax.swing.JPanel {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    /** Creates new form southPanel */
    public southPanel() {
        initComponents();
        //screenSize.width
        //totalSite.HORIZONTAL(150);
    }
    void changeText(int noTotal,int noUp,int noDown,int noFaulty,int noDeactivated,int noCellDwon){
        totalSite.setText("Total Swap Site : "+noTotal);
        upSite.setText("No of UP Site : "+noUp);
        downSite.setText("No of Down Site : "+noDown);
        faultySite.setText("No of Faulty Site : "+noFaulty);
        deactivatedSite.setText("No of Deactivated Site : "+noDeactivated);
        cellDownSite.setText("No of CellDown Site : "+noCellDwon);
    }
    void printname(String Name){
        System.out.println(Name);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalSite = new javax.swing.JTextField();
        downSite = new javax.swing.JTextField();
        upSite = new javax.swing.JTextField();
        faultySite = new javax.swing.JTextField();
        deactivatedSite = new javax.swing.JTextField();
        cellDownSite = new javax.swing.JTextField();

        totalSite.setBackground(new java.awt.Color(0, 0, 0));
        totalSite.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        totalSite.setForeground(new java.awt.Color(255, 255, 255));
        totalSite.setText("Total Swap Site : ");
        totalSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        downSite.setBackground(new java.awt.Color(0, 0, 0));
        downSite.setFont(new java.awt.Font("Tahoma", 1, 36));
        downSite.setForeground(new java.awt.Color(255, 51, 51));
        downSite.setText("No of Down Site : ");
        downSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        upSite.setBackground(new java.awt.Color(0, 0, 0));
        upSite.setFont(new java.awt.Font("Tahoma", 1, 36));
        upSite.setForeground(new java.awt.Color(51, 255, 0));
        upSite.setText("No of UP Site : ");
        upSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        faultySite.setBackground(new java.awt.Color(0, 0, 0));
        faultySite.setFont(new java.awt.Font("Tahoma", 1, 36));
        faultySite.setForeground(new java.awt.Color(255, 255, 102));
        faultySite.setText("No of Faulty Site : ");
        faultySite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        deactivatedSite.setBackground(new java.awt.Color(0, 0, 0));
        deactivatedSite.setFont(new java.awt.Font("Tahoma", 1, 36));
        deactivatedSite.setForeground(new java.awt.Color(153, 153, 153));
        deactivatedSite.setText("No of Deactivated Site :");
        deactivatedSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        cellDownSite.setBackground(new java.awt.Color(0, 0, 0));
        cellDownSite.setFont(new java.awt.Font("Tahoma", 1, 36));
        cellDownSite.setForeground(new java.awt.Color(255, 204, 153));
        cellDownSite.setText("No of CellDown Site :");
        cellDownSite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deactivatedSite, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(downSite)
                    .addComponent(totalSite, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellDownSite)
                    .addComponent(faultySite)
                    .addComponent(upSite, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalSite, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upSite, 0, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downSite, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deactivatedSite, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(faultySite, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cellDownSite, 0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cellDownSite;
    private javax.swing.JTextField deactivatedSite;
    private javax.swing.JTextField downSite;
    private javax.swing.JTextField faultySite;
    private javax.swing.JTextField totalSite;
    private javax.swing.JTextField upSite;
    // End of variables declaration//GEN-END:variables

}
